[project]
name = "gesichterkennung"
version = "0.1.0"
description = "requirements for gesichterkennung"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
]
